@startuml
!define osaPuml https://raw.githubusercontent.com/Crashedmind/PlantUML-opensecurityarchitecture2-icons/master
!include osaPuml/Common.puml
!include osaPuml/User/all.puml
!include osaPuml/Hardware/all.puml
!include osaPuml/Misc/all.puml
!include osaPuml/Server/all.puml
!include osaPuml/Site/all.puml
!include <C4/C4_Context.puml>
!include <c4/C4_Container.puml>
!include <office/Users/user.puml>
LAYOUT_WITH_LEGEND()
title Container context
System_Ext(Imdb,"Imdb API","imdb.com: external API to get information")
System_Ext(Pictures, "Google Images API", "use google lens api to get information")
Person(NotLoggedUser, User, "Not logged user")
Person(LoggedUser, User, "Logged user")
osa_server(gateWay, "Gate Way", "Linux - Ubuntu, Apache Tomcat , Spring Boot Gateway")
osa_server(balancer, "Balancer", "Linux - Unbuntu, Apache")

osa_server(Host3,"Host 3 - Virtual", "Linux - Ubuntu") {
    System_Boundary(BD,"BD") {
        ContainerDb(DataBase,"Data base", "MySQL", "We don't include replic")
    }
}

osa_server(Host4,"Host 4 - Virtual", "Linux - Ubuntu (Scaling up - vertical: increasing memory and CPU )") {
    System_Boundary(ServerBackEnd,"BackEnd") {
        Container(ServiceHost1, "Backend", "Apache Tomcat,Spring boot", "Set of services without state")
        Rel(ServiceHost1,Imdb,"https/JSON")
        Rel(ServiceHost1,Pictures,"https/JSON")
        Rel(ServiceHost1,BD, "JPA/SQL")
    }
}

osa_server(Host1,"Host 1 - Virtual", "Linux - Ubuntu, Apache Tomcat") {
    System_Boundary(MoviesApp,"Movies App") {
        Container(FrontHost1, "FrontEnd", "Angular", "Interaction of the user with the App")

        Rel(FrontHost1, ServiceHost1, "https/JSON")

    }
}

osa_server(Host2,"Host 2 - Virtual", "Linux - Ubuntu, Apache Tomcat") {
    System_Boundary(MoviesApp2,"Movies App") {
        Container(FrontHost2, "FrontEnd", "Angular", "Interaction of the user with the App")
        Rel(FrontHost2, ServiceHost1, "https/JSON")
    }
}

Rel(gateWay, balancer, "https")
Rel(balancer, Host1, "https")
Rel(balancer, Host2, "https")
Rel(NotLoggedUser,gateWay, "https")
Rel(LoggedUser,gateWay, "https")
footer %filename() this is a system which is composed of a website where users can consult information related to movies
@enduml